inherit_gem:
  betterlint:
    - config/default.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - gemfiles/*.gemfile
    - gemfiles/vendor/**/*
    - vendor/**/*

Betterment/ActiveJobPerformable:
  Enabled: false

Betterment/UnscopedFind:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*.gemfile'
