inherit_gem:
  betterlint:
    - config/default.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1
  Exclude:
    - gemfiles/*.gemfile
    - gemfiles/vendor/**/*
    - vendor/**/*
    - spec/dummy/db/schema.rb

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Betterment/ActiveJobPerformable:
  Enabled: false

Betterment/UnscopedFind:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - "gemfiles/*.gemfile"
